name: publish

on:
  pull_request:
    branches: [main]
    types: [opened, closed]
  push:
    branches: ['**']
    
# Note that branches: ['**'] disables workflow when pushing tags
# The above  "on:"" triggers workflows twice after closing a PR. One for PR and one for push.

jobs:
  publish:
    runs-on: [windows-latest]
    steps:
      - name: Build
        run: echo "Project built"
      - name: Publish
        if: github.event.pull_request.merged == true
        run: echo "Package published"
      - name: GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"