name: publish

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, closed]

jobs:
  publish:
    runs-on: [windows-latest]
    steps:
      - name: Build
        run: echo "Project built"
      - name: Publish
        if: github.event.pull_request.merged == true
        run: echo "Package published"