name: publish

on:
  pull_request:
    branches: [publish]
    types: [closed]

jobs:
  publish:
    runs-on: [windows-latest]
    if: github.event.pull_request.merged == true
    steps:
      - name: Publish
        run: echo "Package published"