name: publish

env:
  publish-branch: publish

on:
  pull_request:
    branches: ['publish']
    types: [closed]
  push:
    branches: ['feature/**', 'KLDKB**', 'main']
    tags-ignore: ['**']


#  pull_request:
#    branches: [main]
#    types: [opened, closed]
#
# Note that branches: ['**'] disables workflow when pushing tags
# The above  "on:"" triggers workflows twice after closing a PR. One for PR and one for push.
# The only issue with above approach is that it triggers the workflow twice after succesful PR
# But it allows developer to trigger workflow while making changes
# bash tag-release.sh --branch publish --type build

jobs:
  publish:
    runs-on: [windows-latest]
    steps:
      - name: Build
        run: echo "Project built"
      - name: Publish
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'main') == true
        run: |
          cat README.md
          echo "Package published" 
      - name: GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"