name: publish

on:
  pull_request:
    branches: [main]
    #types: [closed]

jobs:
  publish:
    runs-on: [windows-latest]
    steps:
      - name: Build
        run: echo "Project built"
      - name: Publish
        if: github.event.pull_request.merged == true && github.event.pull_request.types == "closed"
        run: echo "Package published"